### PR TITLE
Configuring assembly references

### PR DESCRIPTION
**Pull request by jweibel22**

### CODE REVIEW

**Comment by Vannevelj** [comment]
In this piece of code we're ignoring a few diagnostic codes, including one that is about not being able to find a certain type: https://github.com/Vannevelj/RoslynTester/blob/master/RoslynTester/RoslynTester/Helpers/DiagnosticVerifier.cs#L329

Would you agree that the check for `CS0246` should be removed then? With your changes this problem can be resolved.
Perhaps we can make it optional and pass it along through another `Configure` setting? `Configure.WithIgnoredWarningCode("CS0246")` for example.

**Comment by jweibel22** [comment]
Yeah, I think it's better to add the missing assembly than to ignore CS0246. I think ignoring build errors will reduce the confidence you can have in the test suite discovering actual bugs in the codefix providers.

**Comment by Vannevelj** [comment]
@jweibel22 in line with #30 I think we should be able to provide a separate `Configure` object on a test-by-test basis. Then we can give separate tests a separate configuration (like compiling with `unsafe` in one test but not another one.

I _think_ this is how your implementation currently works, right? Am I correct when I say that the `Configure.WithAssemblyReference()` in one method will never be used in another one? If that's the case then we can just adapt `VerifierConfiguration` to include more options.

**Comment by jweibel22** [comment]
Yes that's correct, at least when using NUnit or MsTest. It gets initialized in the constructor of the test class, and in Nunit and MsTest an instance of the test class is created for each test case. (that probably also holds for other test frameworks)

I think it sounds like a good idea to expand the Configure to hold other configuration properties as well...

**Pull request closed without merging**
